name: Colab Badges
on:
  push:
    branches:
      - "*"
    paths:
      - '**.ipynb'
jobs:
  build:
    name: Insert Colab Badges
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add/update badges
        uses: trsvchn/colab-badge-action@v3
        with:
          check: 'all'
          update: true
      - uses: EndBug/add-and-commit@v7
        with:
            default_author: github_actions
