name: Docker publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Run unit tests in tox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install apt dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install -yq libpq-dev gcc gcc-10 make libgsl-dev
      - name: Install Python dependencies
        run: python -m pip install -q poetry tox
      - name: Check that gsl-config is in the $PATH
        run: gsl-config --version
      - name: Run tox tests
        run: |
          tox --