name: Docker publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Run unit tests in tox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq libpq-dev gcc make
      - name: Install Python dependencies
        run: python -m pip install -q poetry tox
      - name: Install GNU GSL from source
        run: |
          wget -O gsl-2.6.tar.gz ftp://ftp.gnu.org/gnu/gsl/gsl-2.6.tar.gz
          tar -xf gsl-2.6.tar.gz
          cd gsl-2.6
          ./configure
          make
          make check
          make install
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(realpath ./lib)"
      - name: Check that gsl-config is in the $PATH
        run: gsl-config --version
      - name: Run tox tests
        run: |
          tox --